"""
Django settings for BlogProject project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l=ildokp$!efu15v@gsdm#$al^tpypxwj)p61o06zb@4bnj%ao'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
if not DEBUG:  # Chỉ trong production
    REST_FRAMEWORK = {
        'DEFAULT_RENDERER_CLASSES': (
            'rest_framework.renderers.JSONRenderer',
        ),
    }


ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'your-production-domain.com', '103.20.102.42']
DOMAIN = 'http://127.0.0.1:8000'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels', #django chanel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'oauth2_provider',
    'BlogApp.apps.BlogappConfig',
    'ChatApp.apps.ChatappConfig',
    'rest_framework_mongoengine',
    'django_filters',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        # 'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware', #oauth2
    'corsheaders.middleware.CorsMiddleware',  # Cấu hình cors cho phép người dùng có thể fetapi dù khác domain
    # 'BlogApp.middleware.RequestLoggingMiddleware',
    'BlogApp.middleware.FileSizeLimitMiddleware',
    'BlogApp.middleware.FileExtensionWhitelistMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:8000',  # Local domain
    'http://103.20.102.42:8000',  # Production domain
]
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://103.20.102.42/']


ROOT_URLCONF = 'BlogProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
MEDIA_ROOT = '%s/BlogApp/static/' % BASE_DIR

WSGI_APPLICATION = 'BlogProject.wsgi.application'
#cấu hình django chanel
ASGI_APPLICATION = 'BlogProject.asgi.application'

import os
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
import pymysql
pymysql.install_as_MySQLdb()
# DATABASE_ROUTERS = ['NotificationApp.routers.NotificationRouter']
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'blogdb',
#         'USER': 'AnonymusUser',  # Cập nhật tên người dùng tương ứng
#         'PASSWORD': 'Admin@123',  # Cập nhật mật khẩu tương ứng
#         'HOST': 'db',  # Sử dụng tên dịch vụ 'db' như đã định nghĩa trong docker-compose.yml
#         'PORT': '3306',  # Cổng MySQL mặc định là 3306
#     },
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blogdb',
        'USER': 'root',  # Cập nhật tên người dùng tương ứng
        'PASSWORD': 'Admin@123',  # Cập nhật mật khẩu tương ứng
        'HOST': '',  # Sử dụng tên dịch vụ 'db' như đã định nghĩa trong docker-compose.yml
        # 'PORT': '3306',  # Cổng MySQL mặc định là 3306
    },
}
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_USER_MODEL = 'BlogApp.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#AUTHENTICATION BACKEND
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'oauth2_provider.backends.OAuth2Backend',
)
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 86400,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400*7,#refreshtoken 7 ngày
    'ROTATE_REFRESH_TOKEN': True,
}
#id:FX4glR4JIGLryn5EaXp4cjh21n8sZvuaqMqTrU1S
#sc:L2DWvzpcf6OW7MFiFanE0y3sEQN6dBxGF93QcAQO8LEZqpUevFwGDbqVxUECr70Iy0BbODuysHAKICax3CkgOSWT6wpVbHd6TSInh4rotyQmMBpdZO9iDUy2l2wODimD
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'taxhuy2001@gmail.com'
EMAIL_HOST_PASSWORD = 'owum fexk zmuh gddj'  # Use the App Password here
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
LOGIN_SUCCESSFULLY_URL = 'http://127.0.0.1:3000/login'
LOGIN_FAIL_URL = 'http://127.0.0.1:3000/login'
#ENDPOINT để đăng nhập trang admin
ADMIN_ENDPOINT = 'aids@u-uf@82d!31/'
#Vstorage
VS_USERNAME = '1f0862c'
"""
gi lại log
"""
import os

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'verbose': {
#             'format': '{levelname} {asctime} {module} {process} {thread} {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': os.path.join(BASE_DIR, 'requests.log'),
#             'formatter': 'verbose',
#         },
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#     },
#     'loggers': {
#         '': {
#             'handlers': ['file', 'console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

#redis setting
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://:Admin@123@reids:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#             'PASSWORD': 'Admin@123',  # Mật khẩu Redis
#         }
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Địa chỉ Redis local
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Không cần mật khẩu vì Redis local không yêu cầu
        }
    }
}

STATICAL_CACHE_TIME = 60*5 #5 phút
CATEGORY_CACHE_TIME = 60*60*24 #24 tiếng
PRODUCT_CACHE_TIME = 60*10 #10 phút

#mongo
from mongoengine import connect, disconnect

# Ngắt kết nối cũ (nếu có)
disconnect(alias='default')

# Tạo kết nối mới mongodb
connect(
    db='chatdb',
    host='localhost',
    port=27017,
    alias='default'
)
