# Generated by Django 5.1.1 on 2024-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_bg',
            field=models.URLField(default='https://hcm03.vstorage.vngcloud.vn/v1/AUTH_e2739f2170d44cfc8cfebf9aa23752b6/BlogApp/UserAvatar/default.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://hcm03.vstorage.vngcloud.vn/v1/AUTH_e2739f2170d44cfc8cfebf9aa23752b6/BlogApp/UserAvatar/default.png', max_length=600),
        ),
    ]
