# Generated by Django 5.0.6 on 2024-07-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='status',
            new_name='visibility',
        ),
    ]
