# Generated by Django 5.0.7 on 2024-08-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_productmedia_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmedia',
            old_name='file',
            new_name='media',
        ),
    ]
