# Generated by Django 5.1.1 on 2024-10-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_user_profile_bg_alter_user_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
