# Generated by Django 5.0.6 on 2024-07-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_rename_status_blog_visibility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('blog', 'user')},
        ),
    ]
