# Generated by Django 5.0.7 on 2024-08-31 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_rename_file_productmedia_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='work',
        ),
        migrations.CreateModel(
            name='JobPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.jobpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.tag')),
            ],
            options={
                'unique_together': {('job_post', 'tag')},
            },
        ),
    ]
