# Generated by Django 5.0.6 on 2024-08-01 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
