# Generated by Django 5.0.7 on 2024-09-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_tag_remove_jobpost_work_jobposttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='age',
            field=models.CharField(max_length=5),
        ),
    ]
