# Generated by Django 5.0.6 on 2024-08-04 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('ward', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_date', models.DateField()),
                ('workers_number', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.location')),
            ],
        ),
    ]
