# Generated by Django 5.0.6 on 2024-08-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_location_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('apply_link', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='BlogApp.company')),
            ],
        ),
    ]
