# Generated by Django 5.1.1 on 2024-10-18 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_permission_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_bg',
            field=models.URLField(default='https://hcm03.vstorage.vngcloud.vn/v1/AUTH_e2739f2170d44cfc8cfebf9aa23752b6/BlogApp/UserBackground/default.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='BlogApp.role'),
        ),
    ]
