# Generated by Django 5.1.1 on 2024-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vstorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VstorageCreadentialUsername', models.CharField(max_length=255, unique=True)),
                ('VstorageCreadentialPassword', models.CharField(max_length=255)),
                ('ProjectID', models.CharField(max_length=255, unique=True)),
                ('X_Subject_Token', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
