# Generated by Django 5.0.6 on 2024-08-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_recruitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.location'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='cv/%Y/%m')),
                ('status', models.CharField(choices=[('pending', 'Đang đợi xét duyệt'), ('approved', 'Duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='BlogApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
