# Generated by Django 5.1.1 on 2024-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_vstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_bg',
            field=models.URLField(default='https://hcm03.vstorage.vngcloud.vn/v1/AUTH_f2ecf7a1f0494cdf954303888b0e5df1/MediaOfBlogApp/UserBackground/default.png', max_length=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://hcm03.vstorage.vngcloud.vn/v1/AUTH_f2ecf7a1f0494cdf954303888b0e5df1/MediaOfBlogApp/UserAvatar/default.png', max_length=600),
        ),
    ]
