# Generated by Django 5.1.1 on 2024-10-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
