# Generated by Django 5.0.6 on 2024-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_recruitment_created_date_recruitment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang đợi xét duyệt'), ('approved', 'Duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10),
        ),
    ]
