# Generated by Django 5.0.6 on 2024-08-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
