# Generated by Django 5.1.1 on 2024-09-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_alter_user_profile_bg_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'is_active')},
        ),
    ]
