# Generated by Django 5.1.1 on 2024-09-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email', 'is_active')},
        ),
    ]
