# Generated by Django 5.0.6 on 2024-08-04 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0012_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to=settings.AUTH_USER_MODEL),
        ),
    ]
