# Generated by Django 5.0.6 on 2024-08-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_recruitment_owner'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='BlogApp.company')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_group', to='auth.group')),
            ],
        ),
    ]
