# Generated by Django 5.0.6 on 2024-08-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0014_companygroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companygroup',
            options={'permissions': [('edit_company', 'Can edit company'), ('add_user_to_group', 'Can add user to group'), ('remove_user_from_group', 'Can remove user from group'), ('add_recruitment', 'Can add recruitment'), ('delete_recruitment', 'Can delete recruitment'), ('change_recruitment', 'Can change recruitment'), ('full_access_recruitment', 'Full access to recruitment'), ('create_job_application', 'Can create job application'), ('delete_job_application', 'Can delete job application'), ('change_job_application_status', 'Can change job application status'), ('full_access_job_application', 'Full access to job application')]},
        ),
    ]
