# Generated by Django 5.0.6 on 2024-08-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0015_alter_companygroup_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyGroup',
        ),
    ]
