# Generated by Django 4.1.13 on 2024-08-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_delete_companygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitment',
            name='company',
        ),
    ]
