# Generated by Django 5.1.1 on 2024-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_alter_blogmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
