# Generated by Django 5.0.7 on 2024-08-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('experience', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('work', models.IntegerField(choices=[(1, 'Full time'), (2, 'Part time')])),
                ('job_detail', models.TextField()),
                ('salary', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
