# Generated by Django 5.1.1 on 2024-10-07 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0019_alter_groupchat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='img',
            field=models.URLField(max_length=1024, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
    ]
