# Generated by Django 5.0.7 on 2024-08-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0020_jobpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
