# Generated by Django 5.0.7 on 2024-08-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0021_alter_jobpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], default='full-time', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='work',
            field=models.IntegerField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')]),
        ),
    ]
