# Generated by Django 5.0.7 on 2024-08-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0022_jobpost_status_alter_jobpost_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='status',
        ),
    ]
