# Generated by Django 5.1.1 on 2024-10-08 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0022_alter_productmedia_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(max_length=1024, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
