# Generated by Django 5.0.7 on 2024-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0023_remove_jobpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='work',
            field=models.CharField(choices=[('full-time', 'full-time'), ('part-time', 'part-time')], default='full-time', max_length=10),
        ),
    ]
