# Generated by Django 5.0.7 on 2024-08-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0024_alter_jobpost_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='owner',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='BlogApp.jobpost'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
    ]
