# Generated by Django 5.0.7 on 2024-08-15 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0025_remove_jobapplication_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='likes_count',
        ),
    ]
