# Generated by Django 5.0.7 on 2024-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0026_remove_blog_comments_count_remove_blog_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='age',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
