# Generated by Django 5.0.7 on 2024-08-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0028_category_banner_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BlogApp.product')),
            ],
            options={
                'unique_together': {('product', 'category')},
            },
        ),
    ]
