# Generated by Django 5.0.7 on 2024-08-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0030_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='created_by',
            new_name='user',
        ),
    ]
