# Generated by Django 5.0.7 on 2024-08-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0032_grouppriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
