# Generated by Django 5.0.7 on 2024-08-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0038_alter_user_options_remove_user_unique_active_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
