# Generated by Django 5.0.7 on 2024-08-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0039_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
