# Generated by Django 5.0.7 on 2024-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0040_jobpost_created_date_jobpost_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
