# Generated by Django 5.0.7 on 2024-08-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0042_filemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
