# Generated by Django 5.0.7 on 2024-08-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0044_alter_banner_image_alter_blogmedia_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='blogmedia',
            name='file',
            field=models.FileField(upload_to='blog_media/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='comment/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ImageField(upload_to='products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_bg',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m'),
        ),
    ]
