# Generated by Django 5.0.7 on 2024-08-29 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0046_alter_banner_image_alter_blogmedia_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='icon/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])])),
                ('about', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)])),
                ('phone_number', models.CharField(max_length=20)),
                ('mail', models.EmailField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
